language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - nightly
before_script:
    - curl -s https://getcomposer.org/installer | php
    - php composer.phar install
script: phpunit -c phpunit.xml.dist
matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
